services:
  db-dev:
    image: mongo
    hostname: container_1
    env_file:
      - ./mongo.env
    restart: always
    ports:
      - '27017:27017'

  db-import:
    image: importmongodb
    build: .
    hostname: container_2
    #volumes:
    #  - ./datasets:/datasets
    env_file:
      - ./mongo.env
